%experiment of psi and delta
global exp_loc;
exp_loc = 'data/210310-guangzhou/K on KBr 3.txt';

%starting point offset for experiment data to be compatible with model
%KBr:   151,366
%Si:    185,400
%SiO2:  1,36
global start_point;
start_point = 151;
global end_point;
end_point = 366;

%lambda range generated by model
global lamda;
exp = load(exp_loc);
% exp = 0.25:0.001:2.5;
lamda = exp(start_point:end_point,1)*1000;

%experiment fit result of substrate nk
global substrate_nk
substrate_file = load('data/210310-guangzhou/KBr-substrate.txt');
substrate_lamda_raw = substrate_file(:,1)*1000;
substrate_nk_raw = substrate_file(:,2);
substrate_nk = interp1(substrate_lamda_raw, substrate_nk_raw, lamda, 'linear');
substrate_nk = substrate_nk + ones(size(substrate_nk))*0.01;

%initial value and boundary for alkali(w_p^2, gama_p, Amp_lorenz, Br_lorenz, w0_lorenz, einf)
global para_al err_bar_al;
% para_al   = [16.1366    0.0178    0.2535    1.3591    2.3765    1.0328];
para_al   = [16   0.03   0];
err_bar_al = [3, 0.03, 0];

%initial value and boundary for incident angle(degree)
global theta0 err_bar_theta;
theta0 = 60*pi/180;
err_bar_theta = 0.1*pi/180;

%Total number of fitting parameters
global fp_num;
fp_num = 4;

%max fitting time
global Max_Running_Time;
Max_Running_Time = 600;

% %Time of reflection
% global reflection_time;
% reflection_time = 1;

%lamda_range1 = 1700:5000;
%lamda_range2 = 5000:6:10000;
%lamda = [lamda_range1,lamda_range2];

%initial value and boundary for silica
%global para_SiO2 err_bar_SiO2;
%para_SiO2 = [1.157    0.908    0.10846    0.0066];
%err_bar_SiO2 = [0 0 0 0];
%err_bar_SiO2 = [0 0 0 0];